AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
plugins:
  - rubocop-rake
  - rubocop-rspec

Gemspec/DevelopmentDependencies:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 150
Metrics/PerceivedComplexity:
  Max: 10
